---
- name: Copy codis-fe binary
  copy: src={{ codis_dir }}/bin/codis-fe dest={{ codis_install_dir }}/bin/codis-fe mode=766

- name: Copy codis-fe assets
  copy: src={{ codis_dir }}/bin/assets dest={{ codis_install_dir }}/bin

- name: Copy codis-fe admin script
  template: src=codis-fe-admin.sh dest={{ codis_install_dir }}/admin/codis-fe-admin.sh mode=766

- name: Restart codis-fe service
  command: "{{ codis_install_dir }}/admin/codis-fe-admin.sh restart"
