#!/usr/bin/env bash

set -x
set -e

d=1
sleep $d; /opt/codis/bin/codis-admin --dashboard=127.0.0.1:18080 --reinit-proxy --addr=127.0.0.1:11080
sleep $d; /opt/codis/bin/codis-admin --dashboard=127.0.0.1:18080 --reinit-proxy --addr=127.0.0.1:11081
sleep $d; /opt/codis/bin/codis-admin --dashboard=127.0.0.1:18080 --reinit-proxy --addr=127.0.0.1:11082

